In [1]:
import numpy as np
import pandas as pd

In [3]:
falsy_values = (0,[],{},'',None,False)

In [6]:
any(falsy_values)

False

In [7]:
np.nan

nan

In [8]:
3 + np.nan

nan

In [9]:
a = np.array([0,1,np.nan,np.nan,4])

In [10]:
a

array([ 0.,  1., nan, nan,  4.])

In [11]:
a.sum()

nan

In [12]:
a.mean()

nan

In [13]:
3 + None

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [20]:
b = np.array([0,1,np.nan,None,4],dtype=float)

In [21]:
b

array([ 0.,  1., nan, nan,  4.])

In [22]:
3 + np.inf

inf

In [23]:
np.inf/3

inf

In [24]:
np.inf/np.inf

nan

In [26]:
c = np.array([0,1,2,np.nan,np.inf,5],dtype=float)

In [27]:
c

array([ 0.,  1.,  2., nan, inf,  5.])

In [28]:
c.sum()

nan

<h3>Checking for nan or inf</h3>

In [29]:
np.isnan(np.nan)

True

In [30]:
np.isinf(np.inf)

True

In [34]:
np.isfinite(np.nan),np.isfinite(np.inf)

(False, False)

In [35]:
np.isnan(np.array([0,1,2,np.nan,np.inf,5]))

array([False, False, False,  True, False, False])

In [36]:
np.isinf(np.array([0,1,2,np.nan,np.inf,5]))

array([False, False, False, False,  True, False])

In [37]:
np.isfinite(np.array([0,1,2,np.nan,np.inf,5]))

array([ True,  True,  True, False, False,  True])

<h3>Filtering them out</h3>

In [39]:
d = np.array([0,1,2,np.nan,np.inf,5])

In [44]:
d[~np.isnan(d)]

array([ 0.,  1.,  2., inf,  5.])

In [45]:
d[~np.isinf(d)]

array([ 0.,  1.,  2., nan,  5.])

In [46]:
d[np.isfinite(d)]

array([0., 1., 2., 5.])

In [47]:
d[np.isfinite(d)].sum()

8.0

In [48]:
d[np.isfinite(d)].mean()

2.0