<h3>Basic Numpy Arrays</h3>

In [1]:
import sys
import numpy as np

In [4]:
a = np.array([1,2,3,4])

In [5]:
b = np.array([0,0.5,1,1.5])

In [9]:
a[0],a[1]

(1, 2)

In [10]:
a[0:]

array([1, 2, 3, 4])

In [11]:
a[1:3]

array([2, 3])

In [12]:
b[[0,1,-1]]

array([0. , 0.5, 1.5])

<h3>Array Data Types</h3>

In [15]:
a.dtype

dtype('int32')

In [16]:
b.dtype

dtype('float64')

In [17]:
np.array([1,2,3,4],dtype='float64')

array([1., 2., 3., 4.])

In [18]:
np.array([1,2,3,4],dtype='int8')

array([1, 2, 3, 4], dtype=int8)

In [20]:
c = np.array(['a','b','c','d'])
c.dtype

dtype('<U1')

In [22]:
d = np.array([{'a':1},sys])
d.dtype

dtype('O')

<h3>Dimensions and Shapes</h3>